services:
- type: web
  name: syst√®me de gestion des archives
  runtime: node
  plan: free
  buildCommand: npm install
  startCommand: npm run dev
  envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: sgae-db
        property: connectionString

databases:
  - name: sgae-db
    plan: free
